; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
; Use 'src_dir' to define the base source directory.
; We'll use 'src_filter' in each environment to pick specific subdirectories.
src_dir = src

[env:esp32cam]
platform = espressif32@5.2.0
board = esp32cam
monitor_speed = 112500
upload_speed = 921600
board_build.arduino.memory_type = dio_qspi
framework = arduino
build_flags = -DCORE_DEBUG_LEVEL=5
                -DBOARD_HAS_PSRAM
board_build.partitions = huge_app.csv
; This is crucial: only include source files from the esp32cam subdirectory
src_filter = +<esp32cam/> -<esp32devkitv1/>

lib_deps =
    madhephaestus/ESP32Servo @ ^3.0.6
    tzapu/WiFiManager @ ^2.0.17
    adafruit/Adafruit GFX Library@^1.11.11
    adafruit/Adafruit SSD1306@^2.5.13

[env:esp32devkitv1]
platform = espressif32
; upload_protocol = espota
; upload_port = 192.168.0.194
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = default.csv
; This is crucial: only include source files from the esp32devkitv1 subdirectory
src_filter = +<esp32devkitv1/> -<esp32cam/>

lib_deps =
    madhephaestus/ESP32Servo @ ^3.0.6
    tzapu/WiFiManager @ ^2.0.17
    adafruit/Adafruit GFX Library@^1.11.11
    adafruit/Adafruit SSD1306@^2.5.13
    arduino-libraries/NTPClient @ ^3.2.1
    ; jandrassy/ArduinoOTA @ ^1.1.0